language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements-py2.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements-py3.txt; fi
  - pip install coveralls codacy-coverage
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
